In [27]:
import pandas as pd

In [28]:
df = pd.read_csv("twilio_logs_6_may_2025.csv")

# Convert to datetime and localize to PDT
df['Start Time'] = pd.to_datetime(df['Start Time'])
df['Start Time'] = df['Start Time'].dt.tz_localize('US/Pacific', ambiguous='NaT')

# Convert to HKT
df['Start Time'] = df['Start Time'].dt.tz_convert('Asia/Hong_Kong')

# Convert to datetime and localize to PDT
df['End Time'] = pd.to_datetime(df['End Time'])
df['End Time'] = df['End Time'].dt.tz_localize('US/Pacific', ambiguous='NaT')

# Convert to HKT
df['End Time'] = df['End Time'].dt.tz_convert('Asia/Hong_Kong')

c:\Users\User\anaconda3\lib\site-packages\dateutil\parser\_parser.py:1207: UnknownTimezoneWarning: tzname PDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
  warnings.warn("tzname {tzname} identified but not understood.  "
c:\Users\User\anaconda3\lib\site-packages\dateutil\parser\_parser.py:1207: UnknownTimezoneWarning: tzname PDT identified but not understood.  Pass `tzinfos` argument in order to correctly return a timezone-aware datetime.  In a future version, this will raise an exception.
  warnings.warn("tzname {tzname} identified but not understood.  "

In [29]:
# Convert columns to datetime if not already
df['Start Time'] = pd.to_datetime(df['Start Time'])
df['End Time'] = pd.to_datetime(df['End Time'])

# Calculate time difference
df['Duration'] = df['End Time'] - df['Start Time']  # this is a timedelta object

# Ensure your Duration column is a timedelta (from previous calculation)
df['Duration_sec'] = df['Duration'].dt.total_seconds()

# Format into "X min Y sec" without '0 days'
df['Duration'] = df['Duration_sec'].apply(
    lambda x: f"{int(x // 60)} min {int(x % 60)} sec"
)

In [30]:
df.head()

,Call Sid,Account Sid,Start Time,End Time,Duration,From,To,Direction,Trunk Sid,Secure Trunking,...,Price,Price Unit,STIR Status,Type,Date Created,SIP Call ID,CNAM,Parent Call Sid,Phone Number Sid,Duration_sec
0,CAda5fa2a83ce28ecced018cd60ed4e230,ACa89eab91df26bccd98bd7a67a0772cb3,2025-05-06 15:56:12+08:00,2025-05-06 15:57:31+08:00,1 min 19 sec,85226968615,85230083999,Incoming,NaN,False,...,-0.02,USD,NaN,Phone,2025-05-06T07:56:12.000Z,NaN,NaN,NaN,PN775e4d65821cda196d04199b431fd313,79.0
1,CA8859825f90f073234ea1d8d0c2b68045,ACa89eab91df26bccd98bd7a67a0772cb3,2025-05-06 15:56:11+08:00,2025-05-06 15:56:12+08:00,0 min 1 sec,85226968615,85230083999,Incoming,NaN,False,...,-0.01,USD,NaN,Phone,2025-05-06T07:56:11.000Z,NaN,NaN,NaN,PN775e4d65821cda196d04199b431fd313,1.0
2,CA4bdf3690460407c5cd6e85752d8df891,ACa89eab91df26bccd98bd7a67a0772cb3,2025-05-06 15:54:24+08:00,2025-05-06 16:06:32+08:00,12 min 8 sec,85229624337,85230088367,Incoming,NaN,False,...,-0.13,USD,NaN,Phone,2025-05-06T07:54:24.000Z,NaN,NaN,NaN,PN054c1c1495df0dc22bfc37dd8be4e785,728.0
3,CAd82f0a3165e2c6e66eb7f998d4260ac0,ACa89eab91df26bccd98bd7a67a0772cb3,2025-05-06 15:52:54+08:00,2025-05-06 16:10:17+08:00,17 min 23 sec,85229624679,85230088367,Incoming,NaN,False,...,-0.18,USD,NaN,Phone,2025-05-06T07:52:54.000Z,NaN,NaN,NaN,PN054c1c1495df0dc22bfc37dd8be4e785,1043.0
4,CAa749e00c6cee77b61b281def8b7b32d4,ACa89eab91df26bccd98bd7a67a0772cb3,2025-05-06 15:48:02+08:00,2025-05-06 15:52:41+08:00,4 min 39 sec,85229624679,85230088367,Incoming,NaN,False,...,-0.05,USD,NaN,Phone,2025-05-06T07:48:02.000Z,NaN,NaN,NaN,PN054c1c1495df0dc22bfc37dd8be4e785,279.0

In [31]:
df.to_csv("twilio_call_logs_06_May.csv", index=False)